name: Terraform Master Workflow

on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  prTitlecheck:
    name: PR title check
    if: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.base.ref == 'main' }}
    uses: ./.github/workflows/pr-title.yaml

  releasePreview:
    name: Release Preview
    uses: ./.github/workflows/release-preview.yaml
    permissions:
      contents: write
      pull-requests: write

  preCommitCheck:
    name: Terraform Checks
    uses: ./.github/workflows/terraform-checks.yaml

  generateDocs:
    name: Generate Terraform Docs
    needs: preCommitCheck
    uses: ./.github/workflows/terraform-docs.yaml

  release:
    name: Release module
    needs: generateDocs
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/release.yaml
